# Generated by Django 5.0 on 2023-12-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('is_percent', models.BooleanField()),
                ('text2', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advantages_Model',
                'verbose_name_plural': 'Advantages_Models',
            },
        ),
        migrations.CreateModel(
            name='Main_Page_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('btn_text', models.CharField(blank=True, max_length=50)),
                ('btn_url', models.URLField()),
                ('logo', models.ImageField(upload_to='mainpage/logo')),
                ('background', models.ImageField(upload_to='mainpage/background')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Main_Page_model',
                'verbose_name_plural': 'Main_Page_Models',
            },
        ),
        migrations.CreateModel(
            name='Menu_Items_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menu_Items_Model',
                'verbose_name_plural': 'Menu_Items_Models',
            },
        ),
    ]
